export const phrasesSub18 = [
  'fiquei obcecado em stalkear alguém nas redes sociais.',
  'fui expulso da sala de aula.',
  'desmaiei na rua.',
  'peguei carona com estranhos.',
  'fui parado por policiais.',
  'andei a cavalo.',
  'quebrei um osso.',
  'quebrei um dente.',
  'criei uma conta falsa nas redes sociais.',
  'tive uma experiência paranormal.',
  'tive algum perfil de rede social hackeado.',
  'roubei algo em uma loja.',
  'tive paralisia do sono.',
  'fiquei preso no elevador.',
  'tentei cortar meu próprio cabelo.',
  'pintei o cabelo de alguma cor estranha.',
  'cantei em um karaokê na frente de várias pessoas.',
  'apareci na TV.',
  'passei mal em um parque de diversões.',
  'corri da polícia.',
  'pedi dinheiro no sinal.',
  'me arrependi imediatamente após enviar uma mensagem.',
  'levei um tapa no rosto.',
  'dei um tapa no rosto de alguém.',
  'participei de uma briga.',
  'chorei no transporte público.',
  'passei mais de dois dias sem tomar banho.',
  'olhei o celular de alguém sem que a pessoa soubesse.',
  'fui demitido.',
  'dormi na rua.',
  'peguei comida do lixo e comi.',
  'consegui algo de graça dando em cima de alguém.',
  'caí na rua porque estava olhando o celular.',
  'tive um vídeo constrangedor postado na internet.',
  'quebrei algo na casa de alguém e escondi.',
  'saí de uma festa ou bar sem pagar.',
  'me gabei por algo que não fiz.',
  'menti tanto sobre algo que acreditei que fosse verdade.',
  'sofri bullying na escola.',
  'segurei a mão da pessoa errada na rua.',
  'fui expulso de uma festa.',
  'postei algo e me arrependi.',
  'roubei dinheiro da carteira dos meus pais.',
  'comi comida que caiu no chão.',
  'comi comida que alguém largou na área de alimentação do shopping.',
  'fiquei com mais de 5 pessoas em uma festa.',
  'beijei alguém que eu não conhecia.',
  'fiquei com o irmão/irmã de um amigo.',
  'dormi no ônibus e perdi o meu ponto.',
  'fiquei apaixonado por algum professor.',
  'fui assaltado.',
  'recebi flores.',
  'menti para meus pais sobre onde estava indo.',
  'fiz xixi em uma piscina do lado dos meus amigos.',
  'usei Crocs.',
  'vomitei na frente de outras pessoas.',
  'soltei pum em um elevador e fingi que não fui eu.',
  'segui a pessoa errada na rua.',
  'deixei meu celular cair na privada.',
  'fui em uma festa sem ser chamado.',
  'beijei alguém famoso.',
  'fiquei com gêmeos.',
  'vomitei e tive que engolir.',
  'gostei mais de um filme do que do seu livro.',
  'entrei em casa pela janela.',
  'ri tanto que fiz um pouco de xixi.',
  'passei o número errado para alguém.',
  'menti para alguém sobre qual era meu nome.',
  'tive o meu nome no SPC.',
  'precisei ir ao médico devido a um objeto estranho preso em meu nariz ou ouvido.',
  'usei identidade falsa para entrar em uma festa.',
  'pesquisei meu nome no Google.',
  'dei de presente algo que ganhei e não gostei.',
  'convenci um amigo a largar a namorada.',
  'apaguei um post porque teve poucas curtidas.',
  'usei a escova de dentes de outra pessoa.',
  'me inscrevi em um reality show.',
  'culpei outra pessoa por um erro meu.',
  'menti sobre um candidato em que votei.',
  'dei um conselho ruim para alguém de propósito.',
]
export const phrasesMore18 = [
  'paguei por conteúdos adultos.',
  'recebi fotos ousadas sem estar esperando.',
  'dancei em cima de uma mesa.',
  'quis ficar com um amigo ou amiga.',
  'dei só uma “passadinha” na casa do ex ou do crush.',
  'beijei alguém depois de ter vomitado.',
  'fui trabalhar bêbado.',
  'dei um beijo triplo.',
  'fiquei com alguém em um carro.',
  'acordei e ainda estava bêbado.',
  'nadei sem roupa em uma praia ou cachoeira.',
  'fiquei com alguém na universidade.',
  'experimentei ver minha orientação sexual.',
  'fingi estar sóbrio na frente dos meus pais.',
  'tirei a roupa em uma festa.',
  'vi meus pais em algum momento de intimidade.',
  'tive um “amigo colorido” ou “amigo com benefícios”.',
  'fiquei com alguém que eu nem sabia o nome.',
  'fiquei com alguém desta roda.',
  'fui num clube para adultos.',
  'fiquei com alguém no meio da rua.',
  'assisti a um filme para maiores de idade.',
  'marquei um encontro e não apareci sem avisar.',
  'fiquei com um vizinho.',
  'flertei com outra pessoa mesmo estando comprometido(a).',
  'disse que eu te amo por educação.',
  'fiquei com alguém comprometido.',
  'fui preso.',
  'dirigi após ter ingerido bebida alcoólica.',
  'fiquei com ex de amigo(a).',
  'entupi a privada no banheiro da casa do(a) parceiro(a).',
  'fiquei com alguém por interesse.',
  'troquei o nome do crush/namorado(a).',
  'tive vontade de sair correndo depois de um beijo.',
  'curti várias fotos antigas de alguém no Instagram para a pessoa me notar.',
  'beijei alguém que um dia jurei que jamais ficaria.',
  'mexi no celular do(a) parceiro(a) por estar desconfiado(a) de algo.',
  'provoquei uma pessoa comprometida.',
  'fui a um encontro às cegas.',
  'fiz simpatia para conquistar ou reconquistar alguém.',
  'fiquei com uma pessoa na frente de outra por vingança.',
  'acordei sem lembrar do nome da pessoa com quem fiquei na noite anterior.',
  '“furei o olho” de ninguém.',
  'cheirei as roupas íntimas de outra pessoa.',
  'cheguei em casa sem lembrar como.',
  'fiquei com irmão/irmã de amigo(a).',
  'disse que "eu te amo" apenas para ficar com alguém.',
  'faltei ao trabalho porque estava morrendo de ressaca.',
  'dancei especialmente para alguém.',
  'usei o Tinder enquanto namorava.',
  'usei uma fantasia ousada.',
  'flertei com um chefe na tentativa de obter uma promoção.',
  'fiz compras no cartão de crédito dos meus pais sem avisar.',
  'falsifiquei meus documentos.',
  'enviei fotos ousadas para a pessoa errada.',
  'fiquei com alguém na cama dos meus pais.',
  'fui carregado para casa depois de dar PT.',
  'me senti atraído(a) pelo pai/mãe de algum amigo.',
  'tive um sonho quente com algum professor.',
  'fiquei tão louco que esqueci o próprio nome.',
  'cheirei minhas roupas íntimas para conferir se estavam sujas.',
  'fiquei constrangido com cenas picantes enquanto assistia a um filme com os meus pais.',
  'mandei a mesma foto ousada para duas pessoas ao mesmo tempo.',
  'tive um sonho quente com alguém que está aqui.',
  'fiquei com alguém do mesmo gênero que eu.',
  'mandei fotos ousadas para alguém.',
  'dormi enquanto estava ficando com alguém.',
  'escondi uma marca no pescoço com uma blusa gola alta ou maquiagem.',
  'fiquei com alguém na praia.',
  'fiquei com alguém na rua.',
  'mergulhei de roupa na piscina em uma festa.',
  'marquei de ficar com alguém do Tinder.',
  'fiquei com alguém no banheiro de uma festa.',
  'usei o Tinder.',
  'fiquei com gêmeos.',
  'fiz uma dieta louca.',
  'fiquei com alguém na universidade.',
  'fiquei com alguém no banheiro de uma festa.',
  'fiquei com alguém 20 anos (ou mais) mais velho que eu',
  'fiquei com uma pessoa e depois mais falei com ela.',
  'vi algum vizinho sem roupa.',
  'fiquei com mais de uma pessoa ao mesmo tempo.',
  'dirigi bêbado.',
]

